name: tres-morros-app
region: atl

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

domains:
  - domain: tresmorroscoliumo.cl
    type: PRIMARY
  - domain: www.tresmorroscoliumo.cl
    type: ALIAS

features:
  - buildpack-stack=ubuntu-22
  - new-nodejs-buildpack=true

services:
  - name: tresmorroscoliumo-github-io
    source_dir: .
    github:
      repo: NikoRNJ/tresmorroscoliumo.github.io
      branch: main
      deploy_on_push: true
    environment_slug: node-js
    http_port: 3000
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 1
    health_check:
      http_path: /api/health-lite
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    build_command: pnpm install --frozen-lockfile && pnpm build
    run_command: >
      pnpm --filter @tresmorros/web start --hostname 0.0.0.0 --port ${PORT:-3000}
    routes:
      - path: /

workers:
  - name: cron-worker
    source_dir: .
    github:
      repo: NikoRNJ/tresmorroscoliumo.github.io
      branch: main
      deploy_on_push: true
    environment_slug: node-js
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 1
    build_command: pnpm install --frozen-lockfile
    run_command: >
      while true; do
        echo "[Cron] Triggering expire-holds...";
        curl -X POST -H "x-cron-secret: ${CRON_SECRET}" ${NEXT_PUBLIC_SITE_URL}/api/jobs/expire-holds;
        echo "\n[Cron] Done. Sleeping 5 minutes...";
        sleep 300;
      done
    envs:
      - key: CRON_SECRET
        scope: RUN_TIME
        value: "define-una-clave"
      - key: NEXT_PUBLIC_SITE_URL
        scope: RUN_TIME
        value: "https://www.tresmorroscoliumo.cl"
    envs:
      # NODE_ENV
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: NODE_ENV
        scope: BUILD_TIME
        value: production

      # URLs del sitio
      - key: NEXT_PUBLIC_SITE_URL
        scope: RUN_TIME
        value: "https://www.tresmorroscoliumo.cl"
      - key: NEXT_PUBLIC_SITE_URL
        scope: BUILD_TIME
        value: "https://www.tresmorroscoliumo.cl"

      - key: NEXT_PUBLIC_SITE_ENV
        scope: RUN_TIME
        value: "production"
      - key: NEXT_PUBLIC_SITE_ENV
        scope: BUILD_TIME
        value: "production"

      - key: PUBLIC_EXTERNAL_URL
        scope: RUN_TIME
        value: "https://www.tresmorroscoliumo.cl"
      - key: PUBLIC_EXTERNAL_URL
        scope: BUILD_TIME
        value: "https://www.tresmorroscoliumo.cl"

      - key: NEXT_PUBLIC_SITE_NAME
        scope: RUN_TIME
        value: "Tres Morros de Coliumo"
      - key: NEXT_PUBLIC_SITE_NAME
        scope: BUILD_TIME
        value: "Tres Morros de Coliumo"

      # Supabase
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_TIME
        value: "https://tfztguqsdeolxxskumjg.supabase.co"
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: BUILD_TIME
        value: "https://tfztguqsdeolxxskumjg.supabase.co"

      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_TIME
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmenRndXFzZGVvbHh4c2t1bWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MjU2NDEsImV4cCI6MjA3ODQwMTY0MX0.rJPmNYxQRtTCKruCtyif7_qk6oJEQ29eluKmkfa-CLA"
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: BUILD_TIME
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmenRndXFzZGVvbHh4c2t1bWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MjU2NDEsImV4cCI6MjA3ODQwMTY0MX0.rJPmNYxQRtTCKruCtyif7_qk6oJEQ29eluKmkfa-CLA"

      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmenRndXFzZGVvbHh4c2t1bWpnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjgyNTY0MSwiZXhwIjoyMDc4NDAxNjQxfQ.6BEnoFAhzJyaMZ5iCayHIQyTMLFFnwdwbbMJ2vcrlO8"
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: BUILD_TIME
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmenRndXFzZGVvbHh4c2t1bWpnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjgyNTY0MSwiZXhwIjoyMDc4NDAxNjQxfQ.6BEnoFAhzJyaMZ5iCayHIQyTMLFFnwdwbbMJ2vcrlO8"

      # Flow (sandbox)
      - key: FLOW_API_KEY
        scope: RUN_TIME
        value: "7E3D3FDF-8C70-4EA0-B30D-789129DLAB01"
      - key: FLOW_API_KEY
        scope: BUILD_TIME
        value: "7E3D3FDF-8C70-4EA0-B30D-789129DLAB01"

      - key: FLOW_SECRET_KEY
        scope: RUN_TIME
        value: "726eb20964ce8450daaf31f01998561ae8c3f7b8"
      - key: FLOW_SECRET_KEY
        scope: BUILD_TIME
        value: "726eb20964ce8450daaf31f01998561ae8c3f7b8"

      - key: FLOW_BASE_URL
        scope: RUN_TIME
        value: "https://sandbox.flow.cl/api"
      - key: FLOW_BASE_URL
        scope: BUILD_TIME
        value: "https://sandbox.flow.cl/api"

      - key: FLOW_FORCE_MOCK
        scope: RUN_TIME
        value: "false"

      - key: FLOW_ALLOW_MOCK_IN_PROD
        scope: RUN_TIME
        value: "true"
      - key: FLOW_ALLOW_MOCK_IN_PROD
        scope: BUILD_TIME
        value: "true"

      - key: FLOW_WEBHOOK_SECRET
        scope: RUN_TIME
        value: "dev-flow-webhook-secret-123"
      - key: FLOW_WEBHOOK_SECRET
        scope: BUILD_TIME
        value: "dev-flow-webhook-secret-123"

      # Observabilidad / Sentry
      - key: SENTRY_DSN
        scope: RUN_TIME
        value: ""
      - key: NEXT_PUBLIC_SENTRY_DSN
        scope: RUN_TIME
        value: ""
      - key: NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE
        scope: RUN_TIME
        value: "0.1"
      - key: NEXT_PUBLIC_SENTRY_REPLAYS_SESSION_SAMPLE_RATE
        scope: RUN_TIME
        value: "0"
      - key: NEXT_PUBLIC_SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE
        scope: RUN_TIME
        value: "1"
      - key: SENTRY_TRACES_SAMPLE_RATE
        scope: RUN_TIME
        value: "0.1"
      - key: SENTRY_PROFILES_SAMPLE_RATE
        scope: RUN_TIME
        value: "0.1"
      - key: SENTRY_AUTH_TOKEN
        scope: BUILD_TIME
        value: ""
      - key: SENTRY_ORG
        scope: BUILD_TIME
        value: ""
      - key: SENTRY_PROJECT
        scope: BUILD_TIME
        value: ""

      # SendGrid
      - key: SENDGRID_API_KEY
        scope: RUN_TIME
        value: "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"
      - key: SENDGRID_API_KEY
        scope: BUILD_TIME
        value: "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"

      - key: SENDGRID_FROM_EMAIL
        scope: RUN_TIME
        value: "nicolas.saavedra5@virginiogomez.cl"
      - key: SENDGRID_FROM_EMAIL
        scope: BUILD_TIME
        value: "nicolas.saavedra5@virginiogomez.cl"

      - key: SENDGRID_FROM_NAME
        scope: RUN_TIME
        value: "Tres Morros de Coliumo"
      - key: SENDGRID_FROM_NAME
        scope: BUILD_TIME
        value: "Tres Morros de Coliumo"

      # Seguridad / panel admin
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        value: "cambia-esto"

      - key: ADMIN_SESSION_SECRET
        scope: RUN_TIME
        value: "super-session-secret"

      - key: CRON_SECRET
        scope: RUN_TIME
        value: "define-una-clave"
